# Generated by Django 3.1.7 on 2021-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isInstructor',
            field=models.BooleanField(default=False),
        ),
    ]
