# Generated by Django 3.1.7 on 2021-03-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_userprofile_isinstructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_rounds', models.IntegerField()),
                ('distributor_present', models.BooleanField(default=True)),
                ('wholesaler_present', models.BooleanField(default=True)),
                ('holding_cost', models.IntegerField()),
                ('backlog_cost', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('info_sharing', models.BooleanField(default=True)),
                ('info_delay', models.IntegerField()),
                ('rounds_completed', models.IntegerField()),
                ('is_default_game', models.BooleanField(default=True)),
                ('starting_inventory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=20)),
                ('downstream_player', models.IntegerField()),
                ('upstream_player', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('backlog', models.IntegerField()),
                ('demand', models.IntegerField()),
                ('incoming_shipment', models.IntegerField()),
                ('outgoing_shipment', models.IntegerField()),
                ('order_placed', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='isInstructor',
            new_name='is_instructor',
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='game.role')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='game.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RoleWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='game.role')),
                ('week', models.ForeignKey(db_column='week_id', on_delete=django.db.models.deletion.PROTECT, to='game.week')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='weeks',
            field=models.ManyToManyField(through='game.RoleWeek', to='game.Week'),
        ),
        migrations.CreateModel(
            name='GameRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.PROTECT, to='game.game')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='game.role')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.userprofile'),
        ),
        migrations.AddField(
            model_name='game',
            name='roles',
            field=models.ManyToManyField(through='game.GameRole', to='game.Role'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(through='game.UserRole', to='game.Role'),
        ),
    ]
