# Generated by Django 3.1.7 on 2021-03-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210314_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
