# Generated by Django 3.1.7 on 2021-03-17 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210316_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='week',
            name='backlog',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='week',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='week',
            name='demand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='week',
            name='incoming_shipment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='week',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='week',
            name='order_placed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='week',
            name='outgoing_shipment',
            field=models.IntegerField(default=0),
        ),
    ]
