# Generated by Django 3.1.7 on 2021-03-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210317_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='order_placed',
            field=models.IntegerField(default=-1),
        ),
    ]
