# Generated by Django 3.1.7 on 2021-03-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210317_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_default_game',
        ),
        migrations.AddField(
            model_name='game',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
