# Generated by Django 3.1.7 on 2021-03-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20210318_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerole',
            name='game',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AlterField(
            model_name='gamerole',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='game.role'),
        ),
        migrations.AlterField(
            model_name='roleweek',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='game.role'),
        ),
        migrations.AlterField(
            model_name='roleweek',
            name='week',
            field=models.ForeignKey(db_column='week_id', on_delete=django.db.models.deletion.CASCADE, to='game.week'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='game.role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='game.userprofile'),
        ),
    ]
